eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
spring:
  kafka:
    bootstrap-servers: kafka:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
