server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE
      routes:
        - id: catalog
          uri: lb://catalog-service
          predicates: [ Path=/products/** ]
        - id: order
          uri: lb://order-service
          predicates: [ Path=/orders/** ]
        - id: inventory
          uri: lb://inventory-service
          predicates: [ Path=/inventory/** ]
        - id: payment
          uri: lb://payment-service
          predicates: [ Path=/payments/** ]
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            authorization-grant-type: authorization_code
            scope: openid,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/ecommerce
